### ISSUE TITLE
Test connection transfer when switching networks

### ISSUE THREAD

**Issue by j-era** [artcom/eppsa-ksm#35]
- [ ] Further tests at the KSM Museum

**Comment by Foxhunt** [comment]
socket.io seems stable, when connection is lost emits are buffered and send our on reconnect.

Sometimes Messages get lost, depending on Device, Browser and conditions to the connection loss.

It is unrealistic to achiev 0% packet loss, so lost Messages must be handled.

**Comment by globz-eu** [comment]
Access point switching decision is made by the clients. We have no influence on it.
Reviewed with @globz-eu

**Comment by j-era** [comment]
- [ ] Further tests at the KSM Museum

**Comment by globz-eu** [comment]
Tests performed successfully
